// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQDJab6_sbaC6lCg3_R0WREphnWsUtElo',
    appId: '1:478329961911:web:d2b3bcf1ce4f363bf97c32',
    messagingSenderId: '478329961911',
    projectId: 'message-board-app-cabfd',
    authDomain: 'message-board-app-cabfd.firebaseapp.com',
    storageBucket: 'message-board-app-cabfd.firebasestorage.app',
    measurementId: 'G-FDLD0JM9D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9qmJPsyEfy7TC63URP-ClURG0aoZveZg',
    appId: '1:478329961911:android:23cb6cc403918b70f97c32',
    messagingSenderId: '478329961911',
    projectId: 'message-board-app-cabfd',
    storageBucket: 'message-board-app-cabfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk7SceECd1t03e2B84G7Bhp9Uqel_D_Ns',
    appId: '1:478329961911:ios:3b416b1444824f56f97c32',
    messagingSenderId: '478329961911',
    projectId: 'message-board-app-cabfd',
    storageBucket: 'message-board-app-cabfd.firebasestorage.app',
    iosBundleId: 'com.example.messageboardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk7SceECd1t03e2B84G7Bhp9Uqel_D_Ns',
    appId: '1:478329961911:ios:3b416b1444824f56f97c32',
    messagingSenderId: '478329961911',
    projectId: 'message-board-app-cabfd',
    storageBucket: 'message-board-app-cabfd.firebasestorage.app',
    iosBundleId: 'com.example.messageboardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQDJab6_sbaC6lCg3_R0WREphnWsUtElo',
    appId: '1:478329961911:web:ab94c4fcbbbf5714f97c32',
    messagingSenderId: '478329961911',
    projectId: 'message-board-app-cabfd',
    authDomain: 'message-board-app-cabfd.firebaseapp.com',
    storageBucket: 'message-board-app-cabfd.firebasestorage.app',
    measurementId: 'G-V4M4F83TTD',
  );
}