// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSaMMJ_tF-lpv4NXfd9JGGzi-HtFWcZ0U',
    appId: '1:301742765835:web:b35c2ae1d7fe5956cc540e',
    messagingSenderId: '301742765835',
    projectId: 'message-board-app-409d7',
    authDomain: 'message-board-app-409d7.firebaseapp.com',
    storageBucket: 'message-board-app-409d7.firebasestorage.app',
    measurementId: 'G-R9QFTL4D8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2PQL9nCBISUHgalf_mLZe6JoVHiQTZWk',
    appId: '1:301742765835:android:499113769403a8bbcc540e',
    messagingSenderId: '301742765835',
    projectId: 'message-board-app-409d7',
    storageBucket: 'message-board-app-409d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-RATxgd02GfytVm5KeHMEgoHwfB-CbEA',
    appId: '1:301742765835:ios:b67afeb411c2c4a1cc540e',
    messagingSenderId: '301742765835',
    projectId: 'message-board-app-409d7',
    storageBucket: 'message-board-app-409d7.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-RATxgd02GfytVm5KeHMEgoHwfB-CbEA',
    appId: '1:301742765835:ios:b67afeb411c2c4a1cc540e',
    messagingSenderId: '301742765835',
    projectId: 'message-board-app-409d7',
    storageBucket: 'message-board-app-409d7.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSaMMJ_tF-lpv4NXfd9JGGzi-HtFWcZ0U',
    appId: '1:301742765835:web:d7c9d5cad6d69951cc540e',
    messagingSenderId: '301742765835',
    projectId: 'message-board-app-409d7',
    authDomain: 'message-board-app-409d7.firebaseapp.com',
    storageBucket: 'message-board-app-409d7.firebasestorage.app',
    measurementId: 'G-EQ1R7CR5JR',
  );
}
